In [2]:
import numpy as np
arr = np.array([2,3,4,6,])

In [4]:
arr


array([2, 3, 4, 6])

In [6]:
arr2 = np.array([[2,4,5,7],[3,5,7,8]]) 
arr2

array([[2, 4, 5, 7],
       [3, 5, 7, 8]])

## - Full with 0 in 3x5 Array

In [ ]:
np.zeros((3,5)) 

## - Full with 1 in 4x7 Array

In [ ]:
np.ones((4,7)) 

In [14]:
np.full((2,5),7) #full with 7 in 2 x 5 - 2D Array

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
 np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])