In [67]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
flat = arr.flatten()

In [73]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
flat[0]

1

In [77]:
flat[4]

5

In [79]:
flat[3:6]

array([4, 5, 6])

In [81]:
flat[3:9]

array([4, 5, 6, 7, 8, 9])

In [83]:
print(flat[ : :2])

[1 3 5 7 9]


In [85]:
b = flat[3:7].copy() # it uses same memory allocation so there's copy method

In [87]:
b

array([4, 5, 6, 7])

In [89]:
b[2]=33333333

In [91]:
b 

array([       4,        5, 33333333,        7])

In [93]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
c=flat.copy()

In [101]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
c[[1,4,6]]

array([2, 5, 7])

In [105]:
c[c<3]

array([1, 2])

In [107]:
 reshaped = c.reshape(3,3)

In [109]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])