In [1]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.sum(arr, axis=1) 

array([ 6, 15, 24])

In [29]:
arr[0:2,1:3] # needed 0 , 1 rows in 1 , 2 column 

array([[2, 3],
       [5, 6]])

In [53]:
arr3d = np.array([[[1,2,3],[4,5,6]] ,
                   [[13,14,15],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [10, 11, 12]]])

In [64]:
arr3d.ndim

3

In [68]:
arr3d.shape

(2, 2, 3)