In [1]:
import numpy as np
arr= np.array([11,2,44,5])

In [5]:
np.mean(arr)

15.5

In [11]:
np.std(arr)

16.77050983124842

In [13]:
np.var(arr)

281.25

In [15]:
np.min(arr)

2

In [17]:
np.max(arr)

44

In [21]:
np.sum(arr)

62

In [23]:
np.prod(arr)

4840

In [25]:
np.median(arr)

8.0

In [29]:
np.percentile(arr,50)

8.0

In [31]:
np.argmin(arr)

1

In [35]:
np.argmax(arr) # find the index of max number

2

In [37]:
np.corrcoef(arr)

1.0

In [39]:
np.unique(arr)

array([ 2,  5, 11, 44])

In [41]:
np.diff(arr)

array([ -9,  42, -39])

In [43]:
np.cumsum(arr)

array([11, 13, 57, 62])

In [45]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.log(arr)

array([2.39789527, 0.69314718, 3.78418963, 1.60943791])

In [49]:
np.exp(arr)

array([5.98741417e+04, 7.38905610e+00, 1.28516001e+19, 1.48413159e+02])